import {
    FetchQuantityData,
  } from "../../index";
  
  export const FetchLastNutritionData = async ({ commit }, payload) => {
    commit("saveLastCategoryData", {
      category: payload.category,
      data: await Promise.all([
        FetchQuantityData("HKQuantityTypeIdentifierDietaryPantothenicAcid", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietarySelenium", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietarySodium", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryThiamin", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryVitaminA", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryEnergyConsumed", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryIron", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryMagnesium", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryManganese", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryMolybdenum", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryNiacin", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryPotassium", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryProtein", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryPhosphorus", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryRiboflavin", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryFatTotal", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryCarbohydrates", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryChloride", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryChromium", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryCholesterol", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryCopper", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryFiber", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryFatSaturated", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryFatMonounsaturated", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryFatPolyunsaturated", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryBiotin", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryCaffeine", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryCalcium", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietarySugar", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryFolate", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryWater", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryIodine", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryVitaminB6", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryVitaminB12", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryVitaminC", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryVitaminD", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryVitaminE", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryVitaminK", {...payload,limit: 1,}),
        FetchQuantityData("HKQuantityTypeIdentifierDietaryZinc", {...payload,limit: 1,}),
      ]),
    });
  };